workflows:
  sample-workflow:
    name: ReactNative CLI Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_center_credentials
      android_signing:
        - solocmrn
      vars:
        PACKAGE_NAME: 'com.cmreactnativecli'
        ARTIFACT_PATH: '$CM_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk' # Explicit path for Android APK
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease  # Builds APK (not AAB)
          ls -la "$CM_BUILD_DIR/android/app/build/outputs/apk/release/"  # Debug: Verify APK exists
      - name: Publish to App Center
        script: |
          echo "Installing App Center CLI..."
          npm install -g appcenter-cli
          echo "Publishing to App Center..."
          echo "Artifact path: $ARTIFACT_PATH"
          ls -la "$ARTIFACT_PATH" || echo "ERROR: APK not found!"
      - name: Debug App Center Access
        script: |
          echo "--- Debug Info ---"
          echo "Organization: $ORGANIZATION_NAME"
          echo "App Name: $APP_CENTER_APP_NAME"
          echo "Token: ${APP_CENTER_TOKEN:0:4}...${APP_CENTER_TOKEN: -4}"
          echo "Artifact: $ARTIFACT_PATH"
          ls -la "$ARTIFACT_PATH"

            # Test API access
          appcenter apps list --token "$APP_CENTER_TOKEN" || echo "❌ Token is invalid!"
          appcenter distribute release \
              --group "Codemagic" \
              --file "$ARTIFACT_PATH" \
              --release-notes "App submission via Codemagic" \
              --app "$ORGANIZATION_NAME/$APP_CENTER_APP_NAME" \
              --token "$APP_CENTER_TOKEN" \
              --quiet
    artifacts:
      - android/app/build/outputs/**/*.apk # Collect APK (optional)
    publishing:
      email:
        recipients:
          - solomon@codemagic.io
